image: node:14.16.0-alpine

include:
  - project: 'wartech/ci-template'
    ref: master
    file:
      - 'common/verify-award-emoji/job-verify-thumbs.yaml'

.cache: &global_cache
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules/
      - .npm/

before_script:
  - which yarn
  - echo registry=https://gitlab.warungpintar.co/api/v4/projects/${CI_PROJECT_ID}/packages/npm/ >> ~/.npmrc
  - echo //gitlab.warungpintar.co/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${NPM_TOKEN} >> ~/.npmrc

stages:
  - pre-test
  - test
  - release

verify-thumbs-up:
  extends: .verify-thumbs
  stage: pre-test

build-test:
  stage: test
  <<: *global_cache
  script:
    - yarn --non-interactive --non-progress
    - yarn test:type
    - yarn build
  only:
    - merge_requests
    - master
  tags:
    - gke-node

unit-test:
  stage: test
  <<: *global_cache
  script:
    - yarn --non-interactive --non-progress
    - yarn test:unit
  only:
    - merge_requests
    - master
  tags:
    - gke-node

release:
  stage: release
  <<: *global_cache
  script:
    - yarn --non-interactive --non-progress
    - yarn build
    - yarn semantic-release
  only:
    - master
  tags:
    - gke-node
