image: node:14.16.0-alpine

.cache: &global_cache
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules/
      - .npm/

before_script:
  - which yarn && apk add --no-cache git
  - echo //gitlab.warungpintar.co/api/v4/projects/{CI_PROJECT_ID}/packages/npm/:_authToken="$GITLAB_NPM_TOKEN" >> ~/.npmrc

variables:
  NPM_TOKEN: ${GITLAB_NPM_TOKEN}

stages:
  - test
  - release

lint:
  stage: test
  <<: *global_cache
  script:
    - yarn --non-interactive --non-progress --ignore-scripts
    - yarn test:lint
  tags:
    - gke

unit-test:
  stage: test
  <<: *global_cache
  script:
    - yarn --non-interactive --non-progress --ignore-scripts
    - yarn test:unit
  tags:
    - gke

release:
  stage: release
  <<: *global_cache
  script:
    - yarn --non-interactive --non-progress --ignore-scripts
    - yarn build
    - yarn semantic-release
  only:
    - master
  tags:
    - gke
