image: node:14

.cache: &global_cache
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules/
      - .npm/

before_script:
  - which yarn
  - echo registry=https://gitlab.warungpintar.co/api/v4/projects/${CI_PROJECT_ID}/packages/npm/ >> ~/.npmrc
  - echo //gitlab.warungpintar.co/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${NPM_TOKEN} >> ~/.npmrc

stages:
  - test
  - release

lint:
  stage: test
  <<: *global_cache
  script:
    - yarn --non-interactive --non-progress
    - yarn test:lint
  tags:
    - gke-node

build-test:
  stage: test
  <<: *global_cache
  script:
    - yarn --non-interactive --non-progress
    - yarn test:type
    - yarn build
  tags:
    - gke-node

unit-test:
  stage: test
  <<: *global_cache
  script:
    - yarn --non-interactive --non-progress
    - yarn test:unit
  tags:
    - gke-node

release:
  stage: release
  <<: *global_cache
  script:
    - yarn --non-interactive --non-progress
    - yarn build
    - yarn semantic-release
  only:
    - master
  tags:
    - gke-node
