image: node:14.16.0-alpine

before_script:
  - which yarn && apk add --no-cache git
  - echo //gitlab.warungpintar.co/api/v4/projects/{CI_PROJECT_ID}/packages/npm/:_authToken="$GITLAB_NPM_TOKEN" >> ~/.npmrc

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .npm/

variables:
  NPM_TOKEN: ${GITLAB_NPM_TOKEN}

stages:
  - test
  - release

lint:
  stage: test
  script:
    - yarn --non-interactive --non-progress --ignore-scripts
    - yarn test:lint
  tags:
    - gke

unit-test:
  stage: test
  script:
    - yarn --non-interactive --non-progress --ignore-scripts
    - yarn test:unit
  tags:
    - gke

release:
  stage: release
  script:
    - yarn --non-interactive --non-progress --ignore-scripts
    - yarn build
    - yarn semantic-release
  only:
    - master
  tags:
    - gke
