/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Warlock Config Schema
 */
export interface Config {
  sources?: Source[];
}
export interface Source {
  /**
   * The name of your services or Remote API
   */
  name: string;
  /**
   * the origin server url, for example: https://warunpintar.co
   */
  origin: string;
  /**
   * Responses API Transform, for example: /api/v1 with value type is Transform
   */
  transforms?: {
    [k: string]: Transform;
  };
}
/**
 * field list transform by http method
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^/".
 */
export interface Transform {
  get?: Field[];
  post?: Field[];
  put?: Field[];
  patch?: Field[];
  delete?: Field[];
}
export interface Field {
  /**
   * field name want to transform, (default: root) for example: root.[].name
   */
  field?: string;
  /**
   * the field type, for example: object | string | number
   */
  type?: string;
  /**
   * field name want to transform, (default: root) for example: root.[].name
   */
  resolvers?: Resolver[];
}
export interface Resolver {
  /**
   * resolve from json or inline-json
   */
  json?: string;
  /**
   * resolve from faker, for example: faker.firstName
   */
  faker?: string;
  /**
   * resolve from some file by path, for example: ./mock/resolver.js
   */
  path?: string;
}
